src/Entity/Offres.php
<?php

namespace App\Entity;

use App\Repository\OffresRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffresRepository::class)]
class Offres
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $anneesexperience = null;

    #[ORM\Column(length: 255)]
    private ?string $offrename = null;

    #[ORM\Column(length: 255)]
    private ?string $connaisance = null;

    #[ORM\Column(length: 255)]
    private ?string $critere = null;

    #[ORM\Column]
    private ?int $experiencerequise = null;

    #[ORM\Column(length: 255)]
    private ?string $formation = null;

    #[ORM\Column(length: 255)]
    private ?string $langue = null;

    #[ORM\Column(length: 255)]
    private ?string $mission = null;

    #[ORM\Column]
    private ?int $onmbres_recruteur = null;

    #[ORM\Column]
    private ?float $salaire = null;

    #[ORM\Column(length: 255)]
    private ?string $specialite = null;

    #[ORM\Column(length: 255)]
    private ?string $tacheprincipale = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\OneToMany(mappedBy: 'registoffre', targetEntity: Registration::class)]
    private Collection $registrationstage;

    #[ORM\ManyToOne(inversedBy: 'nameentreprise')]
    private ?Entreprise $nameentreprise = null;

    public function __construct()
    {
        $this->registrationstage = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAnneesexperience(): ?int
    {
        return $this->anneesexperience;
    }

    public function setAnneesexperience(int $anneesexperience): static
    {
        $this->anneesexperience = $anneesexperience;

        return $this;
    }

    public function getOffrename(): ?string
    {
        return $this->offrename;
    }

    public function setOffrename(string $offrename): static
    {
        $this->offrename = $offrename;

        return $this;
    }

    public function getConnaisance(): ?string
    {
        return $this->connaisance;
    }

    public function setConnaisance(string $connaisance): static
    {
        $this->connaisance = $connaisance;

        return $this;
    }

    public function getCritere(): ?string
    {
        return $this->critere;
    }

    public function setCritere(string $critere): static
    {
        $this->critere = $critere;

        return $this;
    }

    public function getExperiencerequise(): ?int
    {
        return $this->experiencerequise;
    }

    public function setExperiencerequise(int $experiencerequise): static
    {
        $this->experiencerequise = $experiencerequise;

        return $this;
    }

    public function getFormation(): ?string
    {
        return $this->formation;
    }

    public function setFormation(string $formation): static
    {
        $this->formation = $formation;

        return $this;
    }

    public function getLangue(): ?string
    {
        return $this->langue;
    }

    public function setLangue(string $langue): static
    {
        $this->langue = $langue;

        return $this;
    }

    public function getMission(): ?string
    {
        return $this->mission;
    }

    public function setMission(string $mission): static
    {
        $this->mission = $mission;

        return $this;
    }

    public function getOnmbresRecruteur(): ?int
    {
        return $this->onmbres_recruteur;
    }

    public function setOnmbresRecruteur(int $onmbres_recruteur): static
    {
        $this->onmbres_recruteur = $onmbres_recruteur;

        return $this;
    }

    public function getSalaire(): ?float
    {
        return $this->salaire;
    }

    public function setSalaire(float $salaire): static
    {
        $this->salaire = $salaire;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->specialite;
    }

    public function setSpecialite(string $specialite): static
    {
        $this->specialite = $specialite;

        return $this;
    }

    public function getTacheprincipale(): ?string
    {
        return $this->tacheprincipale;
    }

    public function setTacheprincipale(string $tacheprincipale): static
    {
        $this->tacheprincipale = $tacheprincipale;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * @return Collection<int, Registration>
     */
    public function getRegistrationstage(): Collection
    {
        return $this->registrationstage;
    }

    public function addRegistrationstage(Registration $registrationstage): static
    {
        if (!$this->registrationstage->contains($registrationstage)) {
            $this->registrationstage->add($registrationstage);
            $registrationstage->setRegistoffre($this);
        }

        return $this;
    }

    public function removeRegistrationstage(Registration $registrationstage): static
    {
        if ($this->registrationstage->removeElement($registrationstage)) {
            // set the owning side to null (unless already changed)
            if ($registrationstage->getRegistoffre() === $this) {
                $registrationstage->setRegistoffre(null);
            }
        }

        return $this;
    }

    public function getNameentreprise(): ?Entreprise
    {
        return $this->nameentreprise;
    }

    public function setNameentreprise(?Entreprise $nameentreprise): static
    {
        $this->nameentreprise = $nameentreprise;

        return $this;
    }
}

src/Form/OffresType.php
<?php

namespace App\Form;

use App\Entity\Offres;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OffresType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('anneesexperience')
            ->add('offrename')
            ->add('connaisance')
            ->add('critere')
            ->add('experiencerequise')
            ->add('formation')
            ->add('langue')
            ->add('mission')
            ->add('onmbres_recruteur')
            ->add('salaire')
            ->add('specialite')
            ->add('tacheprincipale')
            ->add('ville')
            ->add('nameentreprise')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Offres::class,
        ]);
    }
}

src/Controller/OffresController.php
<?php

namespace App\Controller;

use App\Entity\Offres;
use App\Form\OffresType;
use App\Repository\OffresRepository;
use App\Form\OffreSearchType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;


#[Route('/offres')]
class OffresController extends AbstractController
{
    #[Route('/', name: 'app_offres_index', methods: ['GET'])]
    public function index(OffresRepository $offresRepository): Response
    {
        return $this->render('offres/index.html.twig', [
            'offres' => $offresRepository->findAll(),
        ]);
    }
    #[Route('/viewall', name: 'app_offres_viewall', methods: ['GET'])]
    public function viewall(OffresRepository $offresRepository): Response
    {
        return $this->render('offres/viewall.html.twig', [
            'offres' => $offresRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_offres_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $offre = new Offres();
        $form = $this->createForm(OffresType::class, $offre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($offre);
            $entityManager->flush();

            return $this->redirectToRoute('app_offres_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('offres/new.html.twig', [
            'offre' => $offre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_offres_show', methods: ['GET'])]
    public function show(Offres $offre): Response
    {
        return $this->render('offres/show.html.twig', [
            'offre' => $offre,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_offres_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Offres $offre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(OffresType::class, $offre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_offres_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('offres/edit.html.twig', [
            'offre' => $offre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_offres_delete', methods: ['POST'])]
    public function delete(Request $request, Offres $offre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $offre->getId(), $request->request->get('_token'))) {
            $entityManager->remove($offre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_offres_index', [], Response::HTTP_SEE_OTHER);
    }
    #[Route('/search', name: 'ajax_search', methods: ['GET'])]
    public function searchAction(Request $request, OffresRepository $offresRepository)
    {
        $em = $this->getDoctrine()->getManager();

        $requestString = $request->get('q');

        $offres = $em->getRepository(Offres::class)->findEntitiesByString($requestString);

        if (!$offres) {
            $result['offrename']['error'] = "NOT FOUND";
        } else {
            $result['offrename'] = $this->getRealEntities($offres);
        }

        return new Response(json_encode($result));
    }

    public function getRealEntities($offres)
    {

        foreach ($offres as $offre) {
            $realEntities[$offre->getId()] = $offre->getOffrename();
        }
        return $realEntities;
    }

    #[Route('/view', name: 'app_products_View', methods: ['GET', 'POST'])]
    public function View(Request $request, OffresRepository $offresRepository): Response
    {
        $offres = $offresRepository->findAll();
        $form = $this->createForm(OffreSearchType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $searchquery = $form->getData()['offrename'];
            $offres = $offresRepository->search($searchquery);
        }
        return $this->render('offres/view.html.twig', [
            'offres' => $offres,
            'form' => $form->createView()
        ]);
    }
}

templates/offres/_delete_form.html.twig
<form method="post" action="{{ path('app_offres_delete', {'id': offre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ offre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/offres/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/offres/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Offres{% endblock %}

{% block body %}
    <h1>Edit Offres</h1>

    {{ include('offres/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_offres_index') }}">back to list</a>

    {{ include('offres/_delete_form.html.twig') }}
{% endblock %}

templates/offres/index.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Offres
{% endblock %}

{% block body %}
	<h1>Offres</h1>

	<table class="table" id="t">
		<thead>
			<tr>
				<th>Id</th>
				<th>Anneesexperience</th>
				<th>Offrename</th>
				<th>Connaisance</th>
				<th>Critere</th>
				<th>Experiencerequise</th>
				<th>Formation</th>
				<th>Langue</th>
				<th>Mission</th>
				<th>Onmbres_recruteur</th>
				<th>Salaire</th>
				<th>Specialite</th>
				<th>Tacheprincipale</th>
				<th>Ville</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody id="myTable">
			{% for offre in offres %}
				<tr>
					<td>{{ offre.id }}</td>
					<td>{{ offre.anneesexperience }}</td>
					<td>{{ offre.offrename }}</td>
					<td>{{ offre.connaisance }}</td>
					<td>{{ offre.critere }}</td>
					<td>{{ offre.experiencerequise }}</td>
					<td>{{ offre.formation }}</td>
					<td>{{ offre.langue }}</td>
					<td>{{ offre.mission }}</td>
					<td>{{ offre.onmbresRecruteur }}</td>
					<td>{{ offre.salaire }}</td>
					<td>{{ offre.specialite }}</td>
					<td>{{ offre.tacheprincipale }}</td>
					<td>{{ offre.ville }}</td>
					<td>
						<a href="{{ path('app_offres_show', {'id': offre.id}) }}">show</a>
						<a href="{{ path('app_offres_edit', {'id': offre.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="15">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_offres_new') }}">Create new</a>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script>
		$(document).ready(function () {
$("#myInput").on("keyup", function () {
var value = $(this).val().toLowerCase();
$("#myTable tr").filter(function () {
$(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
});
});
});
	</script>
{% endblock %}

templates/offres/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Offres{% endblock %}

{% block body %}
    <h1>Create new Offres</h1>

    {{ include('offres/_form.html.twig') }}

    <a href="{{ path('app_offres_index') }}">back to list</a>
{% endblock %}

templates/offres/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offres{% endblock %}

{% block body %}
    <h1>Offres</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ offre.id }}</td>
            </tr>
            <tr>
                <th>Anneesexperience</th>
                <td>{{ offre.anneesexperience }}</td>
            </tr>
            <tr>
                <th>Offrename</th>
                <td>{{ offre.offrename }}</td>
            </tr>
            <tr>
                <th>Connaisance</th>
                <td>{{ offre.connaisance }}</td>
            </tr>
            <tr>
                <th>Critere</th>
                <td>{{ offre.critere }}</td>
            </tr>
            <tr>
                <th>Experiencerequise</th>
                <td>{{ offre.experiencerequise }}</td>
            </tr>
            <tr>
                <th>Formation</th>
                <td>{{ offre.formation }}</td>
            </tr>
            <tr>
                <th>Langue</th>
                <td>{{ offre.langue }}</td>
            </tr>
            <tr>
                <th>Mission</th>
                <td>{{ offre.mission }}</td>
            </tr>
            <tr>
                <th>Onmbres_recruteur</th>
                <td>{{ offre.onmbresRecruteur }}</td>
            </tr>
            <tr>
                <th>Salaire</th>
                <td>{{ offre.salaire }}</td>
            </tr>
            <tr>
                <th>Specialite</th>
                <td>{{ offre.specialite }}</td>
            </tr>
            <tr>
                <th>Tacheprincipale</th>
                <td>{{ offre.tacheprincipale }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ offre.ville }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_offres_index') }}">back to list</a>

    <a href="{{ path('app_offres_edit', {'id': offre.id}) }}">edit</a>

    {{ include('offres/_delete_form.html.twig') }}
{% endblock %}

templates/offres/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}All Products
{% endblock %}

{% block body %}


	<div class="container">
		<div class="row mb-5 align-items-center">
			<div>
				<h2>
					<center>All Products</center>


				</h2>
			</div>

		</div>

		<div class="input-group custom-search-form">
			<input type="text" id="search" class="form-control" placeholder="Search for a product ...">
		</div>
		<br>
		<ul class="list-group" id="side-menu">
			<h6>Result:
				<span></span>
			</h6>

			<ul style="display: block;" class="nav nav-second-level" id="entitiesNav"></ul>
		</ul>
		<!-- jQuery is necessary -->
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

		<script type="text/javascript">
			jQuery(document).ready(function () {
var searchRequest = null;
$("#search").keyup(function () {

var minlength = 1;
var that = this;
var value = $(this).val();
var entitySelector = $("#entitiesNav").html('');
if (value.length >= minlength) {
if (searchRequest != null) 
searchRequest.abort();



searchRequest = $.ajax({
type: "GET",
url: "{{ path('ajax_search') }}",
data: {
'q': value
},
dataType: "text",

success: function (msg) { // we need to check if the value is the same

if (value == $(that).val()) {
var result = JSON.parse(msg);
$.each(result, function (key, arr) {
$.each(arr, function (id, value) {
if (key == 'offres') {
if (id != 'error') {
entitySelector.append('<li class="list-group-item"><h5><a href="/offres/' + id + '">' + value + '</a></h5></li>');
} else {
entitySelector.append('<li class="errorLi">' + value + '</li>');
}
}
});
});
}
}
});
}
});
});
		</script>


	{% endblock %}

templates/offres/viewall.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offres index
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	<style>
		.list-container {
			display: flex;
			flex-wrap: wrap;
			justify-content: space-between;
		}

		.list-item {
			width: calc(25% - 20px); /* Distribute 4 items in a row */
			margin-bottom: 20px;
			border: 1px solid #ccc;
			padding: 10px;
		}
	</style>
{% endblock %}

{% block body %}
	<h1>Offres index</h1>

	<div class="list-container">
		{% for offre in offres %}
			<div class="list-item">
				<p></p>
				<p>
					<strong>Années d'expérience:</strong>
					{{ offre.anneesexperience }}</p>
				<p>
					<strong>Nom de l'offre:</strong>
					{{ offre.offrename }}</p>
				<p>
					<strong>Connaissance:</strong>
					{{ offre.connaisance }}</p>
				<p>
					<strong>Critère:</strong>
					{{ offre.critere }}</p>
				<p>
					<strong>Expérience requise:</strong>
					{{ offre.experiencerequise }}</p>
				<p>
					<strong>Formation:</strong>
					{{ offre.formation }}</p>
				<p>
					<strong>Langue:</strong>
					{{ offre.langue }}</p>
				<p>
					<strong>Mission:</strong>
					{{ offre.mission }}</p>
				<p>
					<strong>Nombre de recruteurs:</strong>
					{{ offre.onmbresRecruteur }}</p>
				<p>
					<strong>Salaire:</strong>
					{{ offre.salaire }}</p>
				<p>
					<strong>Spécialité:</strong>
					{{ offre.specialite }}</p>
				<p>
					<strong>Tâche principale:</strong>
					{{ offre.tacheprincipale }}</p>
				<p>
					<strong>Ville:</strong>
					{{ offre.ville }}</p>
				<a href="{{ path('app_offres_show', {'id': offre.id}) }}">Show</a>
				<a href="{{ path('app_offres_edit', {'id': offre.id}) }}">Edit</a>
				<form id="register-form" method="post" action="{{ path('app_regist_new') }}">
					<input type="hidden" name="register" value="true">
					<button type="submit" class="btn btn-primary text-white py-3 px-4">Register this item</button>
				</form>

			</div>

			{% if loop.index % 4 == 0 %}
				<div style="flex-basis: 100%;"></div>
				<!-- Add an empty div to start a new row -->
			{% endif %}
		{% else %}
			<p>No records found</p>
		{% endfor %}
	</div>

	<a href="{{ path('app_offres_new') }}">Create new</a>
{% endblock %}